// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApp.API.Data;

#nullable disable

namespace MoviesApp.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250408222213_RenameReviewTextToNotes")]
    partial class RenameReviewTextToNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesApp.API.Models.Movie", b =>
                {
                    b.Property<string>("ShowId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("show_id");

                    b.Property<int?>("Action")
                        .HasColumnType("int")
                        .HasColumnName("Action");

                    b.Property<int?>("Adventure")
                        .HasColumnType("int")
                        .HasColumnName("Adventure");

                    b.Property<int?>("AnimeSeriesInternationalTVShows")
                        .HasColumnType("int")
                        .HasColumnName("AnimeSeriesInternationalTVShows");

                    b.Property<int?>("BritishTVShowsDocuseriesInternationalTVShows")
                        .HasColumnType("int")
                        .HasColumnName("BritishTVShowsDocuseriesInternationalTVShows");

                    b.Property<string>("Cast")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cast");

                    b.Property<int?>("Children")
                        .HasColumnType("int")
                        .HasColumnName("Children");

                    b.Property<int?>("Comedies")
                        .HasColumnType("int")
                        .HasColumnName("Comedies");

                    b.Property<int?>("ComediesDramasInternationalMovies")
                        .HasColumnType("int")
                        .HasColumnName("ComediesDramasInternationalMovies");

                    b.Property<int?>("ComediesInternationalMovies")
                        .HasColumnType("int")
                        .HasColumnName("ComediesInternationalMovies");

                    b.Property<int?>("ComediesRomanticMovies")
                        .HasColumnType("int")
                        .HasColumnName("ComediesRomanticMovies");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<int?>("CrimeTVShowsDocuseries")
                        .HasColumnType("int")
                        .HasColumnName("CrimeTVShowsDocuseries");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("director");

                    b.Property<int?>("Documentaries")
                        .HasColumnType("int")
                        .HasColumnName("Documentaries");

                    b.Property<int?>("DocumentariesInternationalMovies")
                        .HasColumnType("int")
                        .HasColumnName("DocumentariesInternationalMovies");

                    b.Property<int?>("Docuseries")
                        .HasColumnType("int")
                        .HasColumnName("Docuseries");

                    b.Property<int?>("Dramas")
                        .HasColumnType("int")
                        .HasColumnName("Dramas");

                    b.Property<int?>("DramasInternationalMovies")
                        .HasColumnType("int")
                        .HasColumnName("DramasInternationalMovies");

                    b.Property<int?>("DramasRomanticMovies")
                        .HasColumnType("int")
                        .HasColumnName("DramasRomanticMovies");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duration");

                    b.Property<int?>("FamilyMovies")
                        .HasColumnType("int")
                        .HasColumnName("FamilyMovies");

                    b.Property<int?>("Fantasy")
                        .HasColumnType("int")
                        .HasColumnName("Fantasy");

                    b.Property<int?>("HorrorMovies")
                        .HasColumnType("int")
                        .HasColumnName("HorrorMovies");

                    b.Property<int?>("InternationalMoviesThrillers")
                        .HasColumnType("int")
                        .HasColumnName("InternationalMoviesThrillers");

                    b.Property<int?>("InternationalTVShowsRomanticTVShowsTVDramas")
                        .HasColumnType("int")
                        .HasColumnName("InternationalTVShowsRomanticTVShowsTVDramas");

                    b.Property<int?>("KidsTV")
                        .HasColumnType("int")
                        .HasColumnName("KidsTV");

                    b.Property<int?>("LanguageTVShows")
                        .HasColumnType("int")
                        .HasColumnName("LanguageTVShows");

                    b.Property<int?>("Musicals")
                        .HasColumnType("int")
                        .HasColumnName("Musicals");

                    b.Property<int?>("NatureTV")
                        .HasColumnType("int")
                        .HasColumnName("NatureTV");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("poster_url");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rating");

                    b.Property<int?>("RealityTV")
                        .HasColumnType("int")
                        .HasColumnName("RealityTV");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int")
                        .HasColumnName("release_year");

                    b.Property<int?>("Spirituality")
                        .HasColumnType("int")
                        .HasColumnName("Spirituality");

                    b.Property<int?>("TVAction")
                        .HasColumnType("int")
                        .HasColumnName("TVAction");

                    b.Property<int?>("TVComedies")
                        .HasColumnType("int")
                        .HasColumnName("TVComedies");

                    b.Property<int?>("TVDramas")
                        .HasColumnType("int")
                        .HasColumnName("TVDramas");

                    b.Property<int?>("TalkShowsTVComedies")
                        .HasColumnType("int")
                        .HasColumnName("TalkShowsTVComedies");

                    b.Property<int?>("Thrillers")
                        .HasColumnType("int")
                        .HasColumnName("Thrillers");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("ShowId");

                    b.ToTable("movies_titles", (string)null);
                });

            modelBuilder.Entity("MoviesApp.API.Models.Rating", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("ShowId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("show_id");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("UserId", "ShowId");

                    b.HasIndex("ShowId");

                    b.ToTable("movies_ratings", (string)null);
                });

            modelBuilder.Entity("MoviesApp.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<int?>("AmazonPrime")
                        .HasColumnType("int")
                        .HasColumnName("AmazonPrime");

                    b.Property<int?>("AppleTVPlus")
                        .HasColumnType("int")
                        .HasColumnName("AppleTVPlus");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<int?>("DisneyPlus")
                        .HasColumnType("int")
                        .HasColumnName("DisneyPlus");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gender");

                    b.Property<int?>("Hulu")
                        .HasColumnType("int")
                        .HasColumnName("Hulu");

                    b.Property<int?>("Max")
                        .HasColumnType("int")
                        .HasColumnName("Max");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("Netflix")
                        .HasColumnType("int")
                        .HasColumnName("Netflix");

                    b.Property<int?>("ParamountPlus")
                        .HasColumnType("int")
                        .HasColumnName("ParamountPlus");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("Peacock")
                        .HasColumnType("int")
                        .HasColumnName("Peacock");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("zip");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("movies_users", (string)null);
                });

            modelBuilder.Entity("MoviesApp.API.Models.Rating", b =>
                {
                    b.HasOne("MoviesApp.API.Models.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesApp.API.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoviesApp.API.Models.Movie", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MoviesApp.API.Models.User", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
